Modpack Version:

Describe the issue:

What steps should be taken to recreate the issue?:

Were there any changes made to the pack? And what were the changes?:

Please provide the crash report or screenshots (use Pastebin for the crash report):

Any additional information:
